### ISSUE TITLE
Update Readme: Installation with MacOS Monterey

### ISSUE THREAD

**Issue by Gustl22** [chris1111/VoodooHDA-OC#10]
To install kext on MacOS Big Sur and Monterey you need to install [Kext Droplet v2](https://github.com/chris1111/Kext-Droplet-Big-Sur/releases)

And then drop the [latest kext from VoodooHda](https://sourceforge.net/projects/voodoohda/)

The links in the README are outdated or don't work on Monterey.

**Comment by chris1111** [comment]
I will test on my HP Prodesk 600 G1 with Monterey 12.6

**Comment by chris1111** [comment]
It does work here, only HDMI
![Screen Shot 2022-10-02 at 5 00 52 PM](https://user-images.githubusercontent.com/6248794/193476204-9d299079-e865-4cc0-8e44-3084dfdeb6e0.png)

**Comment by Gustl22** [comment]
But the links, screenshots, videos and the versions are outdated in the README. I spent hours to get the right tools and versions. If you want I can make a PR to update the readme.

Or do you mean, without HDMI you won't get any outputs? But better than nothing, isn't it? Btw thanks for programming the tools!

**Comment by chris1111** [comment]
it is the same with the older kext version, no difference

**Comment by Gustl22** [comment]
For me, the installation kext fails with VoodooHDA OC on Monterey. The paths to copy the files are wrong. So maybe one can link to the kext droplet.

Also it's much easier to have the latest version be linked in the readme after the "warning". In the forum, all newer kext files are deleted / not available.

But I get it, that the Readme is for the "OC" Version. But we may could add a Monterey section. I don't even know what is recommeded. The droplet or the OC?
