### ISSUE TITLE
Not working on 11.3 Probook 4440s

### ISSUE THREAD

**Issue by antoniojveraa** [chris1111/VoodooHDA-OC#5]
After updating to 11.3 I lost sound in HDMI and speakers. VoodooHDA Control Panel is not workin either.
Any way to solve this? May I use AppleALC? If so, how? since you recommended use VoodooHDA in this machine time ago.

**Comment by lesonky** [comment]
waitting for update

**Comment by chris1111** [comment]
https://github.com/chris1111/VoodooHDA-OC/issues/6
