### ISSUE TITLE
Headphone issue

### ISSUE THREAD

**Issue by koko-js478** [chris1111/VoodooHDA-OC#7]
# Environment

I have recently installed Hackintosh Catalina (v10.15.7) on my laptop (Dell Inspiron 5593). 
![image](https://user-images.githubusercontent.com/26243241/123543685-64c74c80-d715-11eb-91c9-669c598f0d9c.png)

# Issue
The built-in speaker and microphone work fine, but the headphone doesn't.
- Output
There is a headphone output. The sound effects play the sound well, the other sound has noises and they are very low.
![image](https://user-images.githubusercontent.com/26243241/123542788-30ea2800-d711-11eb-8f9b-8bce25322c7e.png)
- Input
Headphone jack input doesn't appear in the input devices.
![image](https://user-images.githubusercontent.com/26243241/123542827-452e2500-d711-11eb-93a7-965e182f2ab1.png)

Thank you for your support, @chris1111

**Comment by ngfuong** [comment]
I have the same problem on Dell XPS 13 9370. Waiting for any fixes!

**Comment by zaffy31** [comment]
Have you been able to fix this issue?

**Comment by ngfuong** [comment]
> Have you been able to fix this issue?

I have. You can check my repo for instructions if you use the same laptop model as mine (xps 9370).
