### ISSUE TITLE
Workaround to get voodooHDA 2.9.7 works on Big Sur 11.5 above and Monterey

### ISSUE THREAD

**Issue by yahgoo** [chris1111/VoodooHDA-OC#8]
I got it to work with a workaround [installVoodooHDAwWorkaround](https://github.com/yahgoo/installVoodooHDA4BSnMont)

Essentially, I used the following commands and restart.
`sudo kmutil load -p /Library/Extensions/voodooHDA.kext`
`sudo touch /Library/Extensions`

Please give it a shot.
Let me know if it helps
 
@chris1111  I hope this will shed some lights to fix the code for voodooHDA

**Comment by chris1111** [comment]
I wil Pin issue thanks

**Comment by yahgoo** [comment]
@chris1111 this method intermittently work. I recorded the boot process and found that when it does not work. OC reports “error: failed to open pci device”

not working
![notWorking](https://raw.githubusercontent.com/yahgoo/installVoodooHDA4BSnMont/main/img/ErrorFailedToOpenPCIdevice.PNG)

working
![working](https://github.com/yahgoo/installVoodooHDA4BSnMont/blob/main/img/voodooHDAWorking.PNG)
