### ISSUE TITLE
Just Kext?

### ISSUE THREAD

**Issue by RobertLowe** [chris1111/VoodooHDA-OC#9]
Is this the same kext as the one here: https://sourceforge.net/p/voodoohda/code/HEAD/tree/tranc/VoodooHDA.xcodeproj/ or has it been modified?

I ask because, I don't have EFI volumes (well, i do but its just a recovery volume i dont use, nothing seems to get copied there except some firmware stuff?), I just have a usb boot key, so I don't think it works with that?

I just want the kext/manual install, ex: I can place it in library/extensions myself.

I'm also kind of suspect of the lack of source code for the installer :( I cant exactly see what it's copying around. Which worries me incase I want to revert changes.

Thanks @chris1111

**Comment by chris1111** [comment]
Hi  the kext come from the source this. is  the v 2.9.2
Open the app right clic Show packages Content
Content/Resources/Scripts and the kext is there
